name: on-push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ALL:
        type: boolean
        required: true
        description: 'Bump all modules?'

permissions:
  contents: write
  pull-requests: read
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  release-modules:
    uses: slingshot-pipelines/workflows/.github/workflows/release-terraform-modules.yml@release-terraform-modules/v0
    with:
      COMPONENT: modules
    secrets: inherit
